# action.yml
name: 'test-pw-workflow'
description: 'Test a workflow on Parallel Works (PW) platform. Before running set the environment variables PW_PLATFORM_HOST and PW_API_KEY.'
inputs:
  pw-user:
    description: 'Name of the PW user'
    type: string
    required: true
  workflow-name:
    description: 'Name of the PW workflow'
    type: string
    required: true
  workflow-parameters:
    description: 'Workflow input parameters in JSON format'
    type: string
    required: true
  resource-names:
    description: '(OPTIONAL) Name of the resources required to run the workflow. Use --- to define multiple resources, e.g. r1---r2.'
    type: string
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pw-user }}
    - ${{ inputs.workflow-name }}
    - ${{ inputs.workflow-parameters }} 
    - ${{ inputs.resource-names }}

